name: Django CI

on:
  push:
    branches: [ "django_testing_ishika" ]
  pull_request:
    branches: [ "django_testing_ishika" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        node-version: [11.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm ci and install
      workingDirectory: application/frontend
      run: |
        npm ci
        npm run build --if-present
    - name: Run Frontend react tests
      workingDirectory: application/frontend
      run: |
        npm test